import type { Metadata } from "next";
import CTAButton from "@/components/CTAButton";
import SourceBadge from "@/components/SourceBadge";
import TimestampChip from "@/components/TimestampChip";
import Reveal from "@/components/Reveal";

export const metadata: Metadata = {
  title: "Methodology - Veilscope",
  description:
   "How Veilscope applies unbiased filters to public filings and defines core metrics.",
};

export default function MethodologyPage() {
  return (
    <div className="container section">
      <Reveal className="page-hero">
        <p className="eyebrow">Methodology</p>
        <h1>Consistent filters, transparent sources</h1>
        <p className="lead">
          Veilscope applies user-defined filters to public filings. It does not provide recommendations or predictions.
        </p>
        <div className="chip-row">
          <SourceBadge />
          <TimestampChip date="2026-02-11" />
        </div>
      </Reveal>

      <Reveal as="section" className="section">
        <div className="section-grid">
          <div className="section-card">
            <h2>Core promise</h2>
            <p className="muted">
              The system filters data you choose, then returns a list that matches those rules. Educational only. Not investment advice.
            </p>
          </div>
          <div className="section-card">
            <h2>Metrics we use</h2>
            <ul className="metrics-list">
              <li>
                <strong>EPS:</strong> Earnings per share from reported filings.
              </li>
              <li>
                <strong>Operating Cash Flow:</strong> Cash generated by core operations.
              </li>
              <li>
                <strong>Revenue:</strong> Reported top‑line sales.
              </li>
              <li>
                <strong>Relative Strength (3M vs QQQ):</strong> 3-month return of a company relative to QQQ over the same window.
              </li>
            </ul>
          </div>
        </div>
      </Reveal>

      <Reveal as="section" className="section">
        <div className="section-grid">
          <div className="section-card">
            <h2>As-of dates</h2>
            <p className="muted">
              Each metric is tied to a filing date. Screens are only as current as the latest available filings.
            </p>
            <div className="chip-row">
              <TimestampChip date="2026-02-11" />
            </div>
          </div>
          <div className="section-card">
            <h2>Known limitations</h2>
            <ul className="metrics-list">
              <li>Filings can lag by weeks depending on company schedules.</li>
              <li>Not all companies report the same fields in the same way.</li>
              <li>Data is updated nightly when new filings appear.</li>
            </ul>
          </div>
        </div>
      </Reveal>

      <Reveal as="section" className="section">
        <div className="section-card">
          <h2>Sources and definitions</h2>
          <p className="muted">Traceable to public filings with clear terminology.</p>
          <div className="hero-actions">
            <CTAButton href="/data-sources" variant="secondary">
              Data Sources
            </CTAButton>
            <CTAButton href="/glossary" variant="ghost">
              Glossary
            </CTAButton>
          </div>
          <SourceBadge />
        </div>
      </Reveal>
    </div>
  )
}