import type { Metadata } from "next";
import CTAButton from "@/components/CTAButton";
import Reveal from "@/components/Reveal";

export const metadata: Metadata = {
  title: "Glossary - Veilscope",
  description: "Plain-English definitions for key Veilscope terms.",
};

const terms = [
  {
    term: "SEC",
    definition: "The U.S. Securities and Exchange Commission, which regulates public markets.",
  },
  {
    term: "EDGAR",
    definition: "The SEC’s public database of company filings.",
  },
  {
    term: "10‑Q",
    definition: "A quarterly financial report filed by public companies.",
  },
  {
    term: "10‑K",
    definition: "An annual financial report filed by public companies.",
  },
  {
    term: "EPS",
    definition: "Earnings per share reported in company filings.",
  },
  {
    term: "Operating Cash Flow",
    definition: "Cash generated by a company’s core operations.",
  },
  {
    term: "Revenue",
    definition: "Total sales reported in filings.",
  },
  {
    term: "Relative Strength",
    definition: "A company’s return compared to a benchmark over the same window.",
  },
  {
    term: "QQQ",
    definition: "An ETF used as a benchmark for relative strength comparisons.",
  },
  {
    term: "As‑of date",
    definition: "The filing date a metric is tied to.",
  },
  {
    term: "Screen",
    definition: "A filtered list created using your thresholds.",
  },
  {
    term: "Screener Reducer",
    definition: "Plain‑English rules that refine a screened list.",
  },
];

export default function GlossaryPage() {
  return (
    <div className="container section">
      <Reveal className="page-hero">
        <p className="eyebrow">Glossary</p>
        <h1>Key terms, plain English</h1>
        <p className="lead">Short definitions for the terms used across Veilscope.</p>
        <div className="page-hero-actions">
          <CTAButton href="/data-sources" variant="secondary">
            Data Sources
          </CTAButton>
          <CTAButton href="/methodology" variant="ghost">
            Methodology
          </CTAButton>
        </div>
      </Reveal>

      <Reveal as="section" className="section">
        <dl className="glossary-list">
          {terms.map((item) => (
            <div key={item.term} className="glossary-item">
              <dt>{item.term}</dt>
              <dd className="muted">{item.definition}</dd>
            </div>
          ))}
        </dl>
      </Reveal>
    </div>
  );
}