import type { Metadata } from "next";
import CTAButton from "@/components/CTAButton";
import DisclosureBanner from "@/components/DisclosureBanner";
import FeatureCard from "@/components/FeatureCard";
import UpdatesFeed from "@/components/UpdatesFeed";
import { APP_URL } from "@/lib/links";
import MiniScreenerDemo from "@/components/MiniScreenerDemo";
import { prisma } from "@/lib/prisma";
import Reveal from "@/components/Reveal";

export const revalidate = 60;

export const metadata: Metadata = {
  title: "Veilscope - Transparent stock screening from SEC filings",
  description:
    "Unbiased screening of U.S. public companies using reported fundamentals. Educational only.",
};

const steps = [
  {
    title: "Configure",
    description: "Set screening thresholds for core fundamentals you control.",
  },
  {
    title: "Screen",
    description: "Run the screen to generate a list of companies.",
  },
  {
    title: "Reduce",
    description:
      "Apply plain-English rules to refine the list without advice or opinions.",
  },
];

const metrics = [
  {
    name: "EPS",
    description: "Earnings per share pulled from reported filings.",
  },
  {
    name: "Operating Cash Flow",
    description: "Cash generated by a company’s core operations.",
  },
  {
    name: "Revenue",
    description: "Top-line sales reported in filings.",
  },
  {
    name: "Relative Strength (3M vs QQQ)",
    description: "Compares 3-month returns to the QQQ benchmark.",
  },
];

export default async function Home() {
  const latestUpdates = await prisma.update.findMany({
    where: { published: true },
    orderBy: { date: "desc" },
    take: 3,
    select: {
      id: true,
      slug: true,
      title: true,
      date: true,
      summary: true,
      tags: true,
      featured: true,
    },
  });

  const updates = latestUpdates.map((item) => ({
    ...item,
    date: item.date.toISOString(),
  }));

  return (
    <div className="home">
      <Reveal as="section" className="container section hero">
        <div className="hero-grid">
        <div className="hero-text">
          <p className="eyebrow">Unbiased fundamentals</p>
          <h1>Unbiased screening from public filings</h1>
          <p className="lead">
            Configure filters, screen, then reduce the list with plain-English rules.
          </p>
          <div className="hero-actions">
            <CTAButton href={APP_URL}>Open the App</CTAButton>
            <CTAButton href="/methodology" variant="secondary">
              See methodology
            </CTAButton>
          </div>
          <DisclosureBanner />
          </div>
          <div className="hero-demo">
            <MiniScreenerDemo />
          </div>
        </div>
      </Reveal>

      <Reveal as="section" className="container section">
        <h2>How it works</h2>
        <div className="card-grid">
          {steps.map((step) => (
            <FeatureCard
              key={step.title}
              title={step.title}
              description={step.description}
              />
          ))}
        </div>
      </Reveal>

      <Reveal as="section" className="container section">
        <h2>What we measure</h2>
        <div className="section-grid">
          {metrics.map((metric) => (
            <div key={metric.name} className="section-card">
              <h3>{metric.name}</h3>
              <p className="muted">{metric.description}</p>
            </div>
          ))}
          <div className="section-card">
            <h3>More metrics coming</h3>
            <p className="muted">We’ll expand coverage as we add historical market data.</p>
          </div>
        </div>
      </Reveal>

      <Reveal as="section" className="container section trust">
        <div className="section-card section-card--compact">
          <h2>Nothing is hidden</h2>
          <p className="muted">Traceable to public filings.</p>
          <ul className="trust-list">
            <li>Direct links to sources</li>
            <li>Clear as-of dates</li>
            <li>Methodology near every claim</li>
          </ul>
          <div className="trust-actions">
            <CTAButton href="/data-sources" variant="secondary">
              Data Sources
            </CTAButton>
            <CTAButton href="/glossary" variant="ghost">
              Glossary
            </CTAButton>
          </div>
        </div>
      </Reveal>

      <Reveal as="section" className="container section">
        <div className="section-header">
          <h2>Latest updates</h2>
          <a className="link" href="/updates">
            View updates
          </a>
        </div>
        <UpdatesFeed status="ready" items={updates} linkBase="/updates" compactFeatured />
      </Reveal>
    </div>
  );
}